
- name: Install proftpd related system packages
  apt: pkg={{ item }} state={{ galaxy_extras_apt_package_state }}
  with_items:
    - proftpd
    - proftpd-mod-pgsql
  when: galaxy_extras_install_packages

- name: Create Galaxy configuration file
  template: src=proftpd.conf.j2 dest={{ proftpd_conf_path }}

- name: Load Proftpd modules
  lineinfile: dest=/etc/proftpd/modules.conf line="{{ item }}"
  with_items:
    - LoadModule mod_sql.c
    - LoadModule mod_sql_passwd.c
    - LoadModule mod_sql_postgres.c
